<?php

/**
 * This file is part of vBuilder Framework (vBuilder FW).
 *
 * Copyright (c) 2011 Adam Staněk <adam.stanek@v3net.cz>
 *
 * For more information visit http://www.vbuilder.cz
 *
 * vBuilder FW is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * vBuilder FW is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with vBuilder FW. If not, see <http://www.gnu.org/licenses/>.
 */

namespace vBuilder\Composer;

use Composer\Composer;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\Script\ScriptEvents;
use Composer\Script\Event;
use Composer\Util\Filesystem;
use Composer\Util\ProcessExecutor;
use Composer\Package\AliasPackage;
use Composer\Package\BasePackage;
use Composer\Package\RootPackage;

/**
 * Composer plugin for vBuilder libraries
 *
 * Reads extra.vbuilder settings from composer.json.
 *
 * @author Adam Staněk (velbloud)
 * @since Jun 5, 2014
 */
class Plugin implements PluginInterface, EventSubscriberInterface {

	/** @var Composer */
	private $composer;

	/** @var IOInterface */
	private $io;

	/** @var FileSystem */
	private $fs;

	public function activate(Composer $composer, IOInterface $io) {
		$this->composer = $composer;
		$this->io = $io;
		$this->fs = new FileSystem;
	}

	public static function getSubscribedEvents() {
		return array(
			ScriptEvents::POST_AUTOLOAD_DUMP => 'onPostAutoloadDump',
		);
	}

	/**
	 * Returns all installed packages (including root)
	 *
	 * @return array
	 */
	private function getPackages() {

		$ourPackages = array();

		// Dependencies
		$installedPackages = $this->composer->getRepositoryManager()
			->getLocalRepository()->getPackages();

		// Root package
		array_unshift($installedPackages, $this->composer->getPackage());

		foreach($installedPackages as $pkg) {

			// Resolve aliases
			while($pkg instanceof AliasPackage)
				$pkg = $pkg->getAliasOf();

			if(!in_array($pkg, $ourPackages))
				$ourPackages[] = $pkg;
		}

		return $ourPackages;
	}

	/**
	 * Returns absolute path to root package
	 *
	 * @param Package
	 * @return string
	 */
	private function getBasePath() {
		return $this->fs->normalizePath(realpath('.'));
	}

	/**
	 * Returns absolute path to given package
	 *
	 * @param Package
	 * @return string
	 */
	private function getInstallPath(BasePackage $package) {
		return ($package instanceof RootPackage)
			? $this->getBasePath()
			: $this->composer->getInstallationManager()->getInstallPath($package);
	}

	/**
	 * On Autoloader dump
	 *
	 * @param Event
	 */
	public function onPostAutoloadDump(Event $event) {

		$fs = $this->fs;
		$process = new ProcessExecutor($this->io);
		$config = $this->composer->getConfig();

		$basePath = $this->getBasePath();
		$vendorDirPath = $fs->normalizePath(realpath($config->get('vendor-dir')));

		$infoPath = $vendorDirPath . '/composer/vbuilder_info.php';
		$info = array(
			'pkg' => array()
		);

		foreach($this->getPackages() as $pkg) {

			$installPath = $this->getInstallPath($pkg);
			$relativePath = $fs->findShortestPath($vendorDirPath, $installPath, TRUE);
			$packageInfoPath = '//VENDOR_DIR/' . $relativePath;

			$tokens = explode('/', $pkg->getName());

			if(count($tokens) == 2) {
				if(!isset($info['pkg'][$tokens[0]]))
					$info['pkg'][$tokens[0]] = array();

				$packageInfo = &$info['pkg'][$tokens[0]][$tokens[1]];
			} else
				$packageInfo = &$info['pkg'][$tokens[0]];

			$packageInfo = array(
				'dir' => $packageInfoPath,
				'configFiles' => array(),
				'robotLoaderDirs' => array()
			);

			$configFile = $installPath . '/config.neon';
			if(file_exists($configFile)) $packageInfo['configFiles'][] = $packageInfoPath . '/config.neon';

			$robotsFile = $installPath . '/netterobots.txt';
			if(file_exists($robotsFile)) $packageInfo['robotLoaderDirectories'][] = $packageInfoPath;

			// Check for fake autoloader-files
			$extra = $pkg->getExtra();
			if(isset($extra['vbuilder']['fake-autoloader-files'])) {
				$files = (array) $extra['vbuilder']['fake-autoloader-files'];
				foreach($files as $path) {
					$bootstrapDirPath = $fs->normalizePath($installPath . '/' . dirname($path));
					if(!is_dir($bootstrapDirPath)) continue;

					$relativePath = $fs->findShortestPath($bootstrapDirPath, $vendorDirPath, TRUE);
					$autoloadPath = var_export('/' . rtrim($relativePath, '/') . '/autoload.php', TRUE);

					$content = <<<BOOTSTRAP_END
<?php

/**
 * @warning This file is automatically generated by Composer.
 * @see https://github.com/vbuilder/composer-plugin
 */

return include __DIR__ . $autoloadPath;

BOOTSTRAP_END
;

					$autoloadFile = $bootstrapDirPath . '/' . basename($path);
					$autoloadFileShort = $fs->findShortestPath($basePath, $autoloadFile);
					$this->io->write('Generating fake autoload in: ' . $autoloadFileShort);
					file_put_contents($autoloadFile, $content);
					if(is_dir("$installPath/.git")) {
						$exitCode = $process->execute(
							'git --git-dir ' . escapeshellarg("$installPath/.git") .
							' --work-tree ' . escapeshellarg($installPath) .
							' update-index --assume-unchanged ' . escapeshellarg($autoloadFile)
						);

						if($exitCode)
							throw new \RuntimeException('Failed to mark ' . $autoloadFileShort . ' as unchanged');
					}
				}
			}
		}

		$content = <<<PACKAGE_INFO_END
<?php

/**
 * This file is automatically merged into \$container->parameters.
 *
 * @warning This file is automatically generated by Composer.
 * @see https://github.com/vbuilder/composer-plugin
 */

\$vendorDir = __DIR__ . '/..';


PACKAGE_INFO_END
;

		ksort($info['pkg']);

		$content .= 'return ' . var_export($info, TRUE) . ";\n";
		$content = str_replace("'//VENDOR_DIR/", "\$vendorDir . '/", $content);

		$this->io->write('Generating vbuilder_info.php');
		file_put_contents($infoPath, $content);

	}
}